"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
$username$hostname\
$directory \
$fill
$character"""

palette = 'Gruvbox Dark Hard'

# ─── Custom colorschemes ───
[palettes.Claude]
accent = '#DA7756'
user = '#A580E0'
red = '#D91C5C'
green = '#1BAF7A'
dark = '#2E2B28'

[palettes."Gruvbox Dark Medium"]
accent = '#5BC2E7'
user = '#d65d0e'
red = '#fb4930'
green = '#b4bb26'
dark = '#665c54'

[palettes."Gruvbox Dark Hard"]
accent = '#5BC2E7'
user = '#d65d0e'
red = '#fb4930'
green = '#b4bb26'
dark = '#504945'

[username]
show_always = true
format = '[$user](bold user)[@](dimmed user)'

[hostname]
ssh_only = false
format = '[$hostname](bold user)[:](dimmed user)'

[directory]
read_only = " 󰌾"
style = 'bold accent'
format = '[$path]($style)[$read_only]($style)'
truncation_length = 3
truncate_to_repo = true

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[time]
disabled = true
 
[fill]
symbol = '·'
style = 'dark'
 
# SYMBOLS
[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "  "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
