# Video Output Driver
profile=gpu-hq
vo=gpu-next
gpu-api=vulkan
video-sync=display-resample
interpolation=yes
deinterlace=yes
audio-device=pulse

# High-Quality Scaling (similar to madVR's Jinc/Catmull-Rom)
scale=ewa_lanczos
cscale=ewa_lanczos
dscale=mitchell
scale-antiring=0.8
cscale-antiring=0.8

# Debanding (removes color banding)c
deband=yes
deband-iterations=4
deband-threshold=35
deband-range=20
deband-grain=8

# Hardware Decoding (reduces CPU usage)
hwdec=auto-safe
hwdec-codecs=all

# General Behavior
keep-open=yes
save-position-on-quit=yes
cursor-autohide=1500
volume=100
volume-max=200

# HDR Settings (Adjust target-peak to your monitor's peak brightness in nits)
target-peak=250
hdr-compute-peak=yes
target-colorspace-hint=yes
tone-mapping=hable
# Uncomment the line below if you have an HDR display and want to try AutoHDR for SDR content
# inverse-tone-mapping=yes

# OSD (On-Screen Display) Settings
# Show timestamp in "current/total" format when seeking
osd-bar=no # Disable progress bar
osd-on-seek=msg-bar
osd-msg3='${time-pos} / ${duration}'
osd-duration=2000
osd-align-x=right
osd-align-y=top

# Language preferences
# Audio language priority (comma-separated, first match is used)
alang=jpn,jp,japanese,eng,en,english
# Subtitle language priority
slang=pob,por,pt-BR,pt,brazilian,portuguese

# Subtitle styling
sub-font='Arimo Nerd Font'
sub-color='#FCBE11'
sub-border-color='#000000'
sub-border-size=3
sub-shadow-offset=2
sub-shadow-color='#00000080'
sub-font-size=48
# sub-bold=yes # bold subtitles font

# Automatic playlist creation for TV shows
autocreate-playlist=same
