seekbarbg_color=#1F1E1C
thumbnail_box_color=#1F1E1C
window_title_color=#EDE8E0
window_controls_color=#EDE8E0
title_color=#EDE8E0
cache_info_color=#EDE8E0
time_color=#EDE8E0
chapter_title_color=#EDE8E0
side_buttons_color=#EDE8E0
middle_buttons_color=#EDE8E0
playpause_color=#EDE8E0
nibble_current_color=#EDE8E0
seekbar_cache_color=#EDE8E0
thumbnail_box_outline=#EDE8E0
seekbarfg_color=#DA7756
seek_handle_color=#DA7756
seek_handle_border_color=#DA7756
nibble_color=#DA7756
hover_effect_color=#DA7756
held_element_color=#DA7756
