#!/usr/bin/env bash
NUM="${1:-0}"
FILENAME="${NUM}.cpp"

if [[ -f $FILENAME ]]; then
    echo "File already exists!"
	echo "opening $FILENAME..."
	code "$FILENAME"
	exit 1
fi


cat > "$FILENAME" << EOF
/*
    CSES ${NUM} - TITLE
    https://cses.fi/problemset/task/${NUM}
*/

EOF
code "$FILENAME"
