#!/bin/bash
NUM="${1:-0}"
FILENAME="cses${NUM}.cpp"
cat > "$FILENAME" << EOF
/*
    CSES ${NUM} - TITLE
    https://cses.fi/problemset/task/${NUM}
*/

#include <bits/stdc++.h>
using namespace std;
using ll = long long;

int main() {
	ios_base::sync_with_stdio(0); cin.tie(0);

    //code

	return 0;
}
EOF
code "$FILENAME"
